version: "3.9"

services:
  api:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
