
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: pavani802/backend:latest  # <- Docker Hub image name
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: pavani802/frontend:latest  # <- Docker Hub image name
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
