name: CI/CD for e2e ML Model Development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests.py

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push backend image
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Build & push frontend image
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Deploy backend on Render
      - name: Deploy Backend on Render
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.BACKEND_SERVICE_ID }}" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      # Deploy frontend on Render
      - name: Deploy Frontend on Render
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.FRONTEND_SERVICE_ID }}" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
